name: Python API CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    uses: Matheus-TecDev/platform-workflows/.github/workflows/python-api-ci.yml@REPLACE_WITH_FULL_COMMIT_SHA
